# This file was generated by GoReleaser. DO NOT EDIT.
cask "gittree" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "2d897d9e87078ea822a182e7b61dc0a01f10b1d4cc871b7ed73a3e511f82fd78"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "34a40da9f276c87d6678dd6ffd1be6b67320c92db456b3275db4b770426056d3"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "73ae7068f3bbfc0446bc99215938acdff75faa2bc35937f6623d0c9a4fe66134"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "40c771028bfe38d5fee02500ccc9e074cc17bd48be992a4b4a1e9d1fce22547a"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gittree"
  desc "Browse the state of every git repository under a directory, as a scrollable tree"
  homepage "https://github.com/schretzi/gittree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gittree"
  manpage "man/gittree-config-init.1"
  manpage "man/gittree-config-path.1"
  manpage "man/gittree-config.1"
  manpage "man/gittree-list.1"
  manpage "man/gittree-version.1"
  manpage "man/gittree.1"
  bash_completion "completions/gittree.bash"
  fish_completion "completions/gittree.fish"
  zsh_completion "completions/gittree.zsh"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gittree"]
    end
  end

  # No zap stanza required
end
