# This file was generated by GoReleaser. DO NOT EDIT.
cask "gittree" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5e49b9e3ebcc22246d507da44bec6252167b8c839bd4d1f3ca5ecdaa20e667fd"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c65f7c4fd85d20413d1d4e4f5cff22246a1943bb286bbca5103aa933867374c"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "976acb626f8592b6e24c90c53b25b8e3d9eb6823a24d1d8faa566a7daf893987"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66aa56ab1fd3ae7da499bcb78a7f4bcad1d0e9e33d4eb5236fd73f4a0b4558d9"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gittree"
  desc "Browse the state of every git repository under a directory, as a scrollable tree"
  homepage "https://github.com/schretzi/gittree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gittree"
  manpage "man/gittree-config-init.1"
  manpage "man/gittree-config-path.1"
  manpage "man/gittree-config.1"
  manpage "man/gittree-list.1"
  manpage "man/gittree-version.1"
  manpage "man/gittree.1"
  bash_completion "completions/gittree.bash"
  fish_completion "completions/gittree.fish"
  zsh_completion "completions/gittree.zsh"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gittree"]
    end
  end

  # No zap stanza required

end
