# This file was generated by GoReleaser. DO NOT EDIT.
cask "gittree" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "32c48dd1e84152e3b9d17b45ec6493eef24aba64c35a5b67f7380b35bd1ed14d"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a656cb1c21071e5b91ffa9c661deecb105c808642f5bb155637f96925b37455a"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3da658fcc274ab77a0dc670ee84ca6cfeffd06226e3a2235283ae2afc633d80"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c19149eb7b3d308fd43005a573f26c9042c2b846d478f37d599efb35ac9a269"
      url "https://github.com/schretzi/gittree/releases/download/v#{version}/gittree_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gittree"
  desc "Browse the state of every git repository under a directory, as a scrollable tree"
  homepage "https://github.com/schretzi/gittree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gittree"
  manpage "man/gittree-config-init.1"
  manpage "man/gittree-config-path.1"
  manpage "man/gittree-config.1"
  manpage "man/gittree-list.1"
  manpage "man/gittree-version.1"
  manpage "man/gittree.1"
  bash_completion "completions/gittree.bash"
  fish_completion "completions/gittree.fish"
  zsh_completion "completions/gittree.zsh"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gittree"]
    end
  end

  # No zap stanza required
end
