# This file was generated by GoReleaser. DO NOT EDIT.
cask "kerberoskeepalive" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "649bb1b62a554c8a0834d01ffed426582f50128d25148a5605c879635b22b24e"
      url "https://github.com/schretzi/KerberosKeepAlive/releases/download/v#{version}/kerberoskeepalive_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5f8e080c0d4002b65a8c5f4c2540a5ff9eb2f6bb7ad1e81485df96c971c8a17"
      url "https://github.com/schretzi/KerberosKeepAlive/releases/download/v#{version}/kerberoskeepalive_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "kerberoskeepalive"
  desc "Keep macOS Kerberos tickets refreshed from Keychain-stored passwords"
  homepage "https://github.com/schretzi/KerberosKeepAlive"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kerberoskeepalive"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kerberoskeepalive"]
    end
  end

  uninstall_preflight do
    # The LaunchAgent plist references this binary by absolute path, so
    # leaving it loaded would make launchd retry a deleted executable
    # forever. Boot it out and remove the plist first.
    system_command "#{staged_path}/kerberoskeepalive",
                   args: ["service", "uninstall"],
                   must_succeed: false
  end

  zap trash: [
      "~/.config/kerberoskeepalive",
      "~/Library/Logs/kerberoskeepalive.log",
      "~/Library/Logs/kerberoskeepalive.err.log",
      "~/Library/LaunchAgents/com.schretzi.kerberoskeepalive.plist",
    ]

  caveats <<~EOS
    This only installs the binary. To have tickets refreshed automatically,
    configure a profile and then load the LaunchAgent:

      kerberoskeepalive init
      kerberoskeepalive daemon install
  EOS
end
