# This file was generated by GoReleaser. DO NOT EDIT.
cask "kerberoskeepalive" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "091efdc38c9cb3cea8ccb79796b7828ac1c5532d8c89497620b6d80e664bae38"
      url "https://github.com/schretzi/KerberosKeepAlive/releases/download/v#{version}/kerberoskeepalive_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d8328f5e01c710a2aee699480d4f6b3efda3396992a99f04d3c6db0ce356c2e"
      url "https://github.com/schretzi/KerberosKeepAlive/releases/download/v#{version}/kerberoskeepalive_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "kerberoskeepalive"
  desc "Keep macOS Kerberos tickets refreshed from Keychain-stored passwords"
  homepage "https://github.com/schretzi/KerberosKeepAlive"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kerberoskeepalive"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kerberoskeepalive"]
    end
  end

  uninstall_preflight do
    # The LaunchAgent plist references this binary by absolute path, so
    # leaving it loaded would make launchd retry a deleted executable
    # forever. The agent's label is per-user
    # (com.<username>.kerberoskeepalive), so a static `launchctl:`
    # stanza can't name it - let the binary boot itself out instead.
    system_command "#{staged_path}/kerberoskeepalive",
                   args: ["daemon", "uninstall"],
                   must_succeed: false
  end

  zap trash: [
      "~/.config/kerberoskeepalive",
      "~/Library/Logs/KerberosKeepAlive",
      "~/Library/LaunchAgents/com.*.kerberoskeepalive.plist",
    ]

  caveats <<~EOS
    This only installs the binary. To have tickets refreshed automatically,
    configure a profile and then load the LaunchAgent:

      kerberoskeepalive init
      kerberoskeepalive daemon install
  EOS
end
