# This file was generated by GoReleaser. DO NOT EDIT.
cask "macswitcher" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "75d273a65a09b482421e088c222338a76ed576b61d8b75f72cacd86214b88b0c"
      url "https://github.com/schretzi/macswitcher/releases/download/v#{version}/macswitcher_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "90177a7e275987c31979757792dd697f6d9b1aa928d6ab7b518558c5016c4635"
      url "https://github.com/schretzi/macswitcher/releases/download/v#{version}/macswitcher_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "macswitcher"
  desc "Manage macOS network contexts, DNS, and proxy services"
  homepage "https://github.com/schretzi/macswitcher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macswitcher"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macswitcher"]
    end
  end

  # No zap stanza required
end
