# This file was generated by GoReleaser. DO NOT EDIT.
cask "macswitcher" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "8a44ab500ce70dca25e8e90fd8010b2f35186dc0ea83e97b3b009ff5ca155dd6"
      url "https://github.com/schretzi/macswitcher/releases/download/v#{version}/macswitcher_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f7023df15c9558ea4c2efaa6d3d79cd658bd80eb990e8eff916f5de4d05c39ed"
      url "https://github.com/schretzi/macswitcher/releases/download/v#{version}/macswitcher_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "macswitcher"
  desc "Manage macOS network contexts, DNS, and proxy services"
  homepage "https://github.com/schretzi/macswitcher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macswitcher"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macswitcher"]
    end
  end

  # No zap stanza required
end
