# This file was generated by GoReleaser. DO NOT EDIT.
cask "macswitcher" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "e27163896e5ebd08bfb23e64509c46f615dd514b28908fef1cea1fdf1f910f43"
      url "https://github.com/schretzi/macswitcher/releases/download/v#{version}/macswitcher_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b2425de1f9480f6ab12fb5f5f455dd50fa1f466a84b41ffd3691d0de8a2c253"
      url "https://github.com/schretzi/macswitcher/releases/download/v#{version}/macswitcher_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "macswitcher"
  desc "Manage macOS network contexts, DNS, and proxy services"
  homepage "https://github.com/schretzi/macswitcher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macswitcher"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macswitcher"]
    end
  end

  # No zap stanza required
end
