# This file was generated by GoReleaser. DO NOT EDIT.
cask "omt" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "d86ae80e8de4267233a567b6690536e47da142acdd25edc86e7e4b6e13049a05"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c4157606b4175cdc8a9c46d358fcd0b9260c7cf93882e0f08a3d84e616f0304"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77984d717e793f1511b66b0f30ff910d0a14ad3528d632dc4847515f063894a9"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1cafa0d75e3f7eaf9f63a677fd351faca9456d3285419ebc29eee059fb965e57"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_linux_amd64.tar.gz"
    end
  end

  name "omt"
  desc "Obtain and print a valid OAuth2 access token for IMAP/POP/SMTP, stored in the OS keyring"
  homepage "https://github.com/schretzi/OauthMailToken"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omt"
  manpage "man/omt-authorize.1"
  manpage "man/omt-daemon.1"
  manpage "man/omt-list-accounts.1"
  manpage "man/omt-refresh.1"
  manpage "man/omt-status.1"
  manpage "man/omt-token.1"
  manpage "man/omt-version.1"
  manpage "man/omt.1"
  bash_completion "completions/omt.bash"
  fish_completion "completions/omt.fish"
  zsh_completion "completions/omt.zsh"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omt"]
    end
  end

  # No zap stanza required
end
