# This file was generated by GoReleaser. DO NOT EDIT.
cask "omt" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "98d721ce00d8642648c2ea9a567290c915d8ef694a467f48c854fb5914a0f866"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0bdaf8c167f63b4f404fe7c7171da3575df959654f5ff8838b20ad7f83caa202"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b47a011662a447d36a11c1d3a8c568ad2e25c23766ed43a8e251b7dcd92aaffb"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "950abf60d88d02aca51a9c1b845948bfa7182a8b4470bafb2edae6942979b489"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_linux_amd64.tar.gz"
    end
  end

  name "omt"
  desc "Obtain and print a valid OAuth2 access token for IMAP/POP/SMTP, stored in the OS keyring"
  homepage "https://github.com/schretzi/OauthMailToken"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omt"
  manpage "man/omt-authorize.1"
  manpage "man/omt-daemon.1"
  manpage "man/omt-list-accounts.1"
  manpage "man/omt-refresh.1"
  manpage "man/omt-status.1"
  manpage "man/omt-token.1"
  manpage "man/omt-version.1"
  manpage "man/omt.1"
  bash_completion "completions/omt.bash"
  fish_completion "completions/omt.fish"
  zsh_completion "completions/omt.zsh"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omt"]
    end
  end

  # No zap stanza required
end
