# This file was generated by GoReleaser. DO NOT EDIT.
cask "omt" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4d9dc098f553949816da3437e9418fafbb747ebe3620f8436be6496bec521241"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92b61ca5c75a60e716acf22d9733b52acc9f71136556e9fc9c1b053d4c634725"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "de68852929799721fce37a04df82b283972576607a6b5285a6cdf23e46cddb4c"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "14c6f9043ef09b45f3a406cdf0cb6197860ccc6cc9098a13c5b082ff39d11f80"
      url "https://github.com/schretzi/OauthMailToken/releases/download/v#{version}/omt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "omt"
  desc "Obtain and print a valid OAuth2 access token for IMAP/POP/SMTP, stored in the OS keyring"
  homepage "https://github.com/schretzi/OauthMailToken"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omt"
  manpage "man/omt-authorize.1"
  manpage "man/omt-daemon.1"
  manpage "man/omt-list-accounts.1"
  manpage "man/omt-refresh.1"
  manpage "man/omt-status.1"
  manpage "man/omt-token.1"
  manpage "man/omt-version.1"
  manpage "man/omt.1"
  bash_completion "completions/omt.bash"
  fish_completion "completions/omt.fish"
  zsh_completion "completions/omt.zsh"

  postflight do
    if OS.mac?
      # The release binaries are not notarized, so Gatekeeper would
      # otherwise refuse to run them after a browser-less download.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omt"]
    end
  end

  # No zap stanza required

end
