# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Macswitcher < Formula
  desc "Manage macOS network contexts, DNS, and proxy services"
  homepage "https://github.com/schretzi/macswitcher"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/schretzi/macswitcher/releases/download/v0.1.0/macswitcher_0.1.0_darwin_amd64.tar.gz"
    sha256 "9b51fabd223a5ad8d06f41b9cd1b3e06d24d51fb038dda6e29cf27d53e651b9f"

    define_method(:install) do
      bin.install "macswitcher"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/schretzi/macswitcher/releases/download/v0.1.0/macswitcher_0.1.0_darwin_arm64.tar.gz"
    sha256 "2eab967ccf9c5b2b86b69cab003f39717790583c08f2f29eb198bdc1e1495337"

    define_method(:install) do
      bin.install "macswitcher"
    end
  end
end
